map_for_starbucks/map/urls.py
from django.urls import path
from . import views

app_name = "map"

urlpatterns = [
    path('', views.MapView.as_view(), name='map'),
    path('excel/', views.ExcelView.as_view(), name='excel'),
    path('excel/update_data/', views.UpdateDataView, name='update_data'),
    path('statistics/', views.StatisticsView.as_view(), name='statistics'),
    path('import_list/', views.import_list.as_view(),name='import_list'),
    path('add_shop/', views.AddShopView.as_view(), name='add_shop'),
]

map_for_starbucks/map_for_starbucks/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('map.urls')),
    path('indexing/', include('indexing.urls')),
]

map_for_starbucks/map/models.py
from django.db import models

# Create your models here.

class ShopList(models.Model):
    postcode = models.CharField(
        verbose_name='postcode',
        max_length=10,
        blank=True,
        null=True,
    )

    address = models.CharField(
        verbose_name='address',
        max_length=150,
        blank=True,
        null=True,
    )

    prefecture = models.CharField(
        verbose_name='prefecture',
        max_length=5,
        blank=True,
        null=True,
    )

    name = models.CharField(
        verbose_name='shopname',
        max_length=150,
        blank=True,
        null=True,
    )

    latitude = models.FloatField(
        verbose_name='latitude',
        blank=True,
        null=True,
    )

    longitude = models.FloatField(
        verbose_name='longitude',
        blank=True,
        null=True,
    )

    drivethrough = models.BooleanField(
        verbose_name='drivethrough',
        blank=True,
        null=True
    )

    businesshour = models.CharField(
        verbose_name='businesshour',
        max_length=500,
        blank=True,
        null=True
    )

    closed = models.BooleanField(
        verbose_name='closed',
        blank=True,
        null=True,
    )

    yuya = models.BooleanField(
        verbose_name='yuya',
        blank=True,
        null=True,
    )

    non = models.BooleanField(
        verbose_name='non',
        blank=True,
        null=True,
    )

    monday = models.CharField(
        verbose_name='monday',
        max_length=50,
        blank=True,
        null=True,
    )

    tuesday = models.CharField(
        verbose_name='tuesday',
        max_length=50,
        blank=True,
        null=True,
    )

    wednesday = models.CharField(
        verbose_name='wednesday',
        max_length=50,
        blank=True,
        null=True,
    )

    thursday = models.CharField(
        verbose_name='thursday',
        max_length=50,
        blank=True,
        null=True,
    )

    friday = models.CharField(
        verbose_name='friday',
        max_length=50,
        blank=True,
        null=True,
    )

    saturday = models.CharField(
        verbose_name='saturday',
        max_length=50,
        blank=True,
        null=True,
    )

    sunday = models.CharField(
        verbose_name='sunday',
        max_length=50,
        blank=True,
        null=True,
    )

    holiday = models.CharField(
        verbose_name='holiday',
        max_length=50,
        blank=True,
        null=True,
    )

    add_day = models.CharField(
        verbose_name = 'add_day',
        max_length = 30,
        blank = True,
        null = True,
    )
    
    yuya_last_visit = models.CharField(
        verbose_name = 'yuya_last_visit',
        max_length = 300,
        blank = True,
        null = True,
    )
    
    yuya_frequency_of_visit = models.IntegerField(
        verbose_name = 'yuya_frequency_of_visit',
        blank = True,
        null = True,
    )
    
    non_last_visit = models.CharField(
        verbose_name = 'non_last_visit',
        max_length = 300,
        blank = True,
        null = True,
    )
    
    non_frequency_of_visit = models.IntegerField(
        verbose_name = 'non_frequency_of_visit',
        blank = True,
        null = True,
    )

    def __str__(self):
        return self.name

map_for_starbucks/map/forms.py
from django import forms

class import_list_form(forms.Form):
    CHOICES = [('yuya', 'yuya'), ('non', 'non')]
    user = forms.ChoiceField(choices=CHOICES, widget=forms.RadioSelect)
    visited_file = forms.FileField(widget=forms.ClearableFileInput(attrs={'accept': 'text/html'}))

from .models import ShopList

class ToDatabeseForm(forms.Form):
    id = forms.CharField(
        label='number',
        max_length=4,
    )

    postcode = forms.CharField(
        label='postcode',
        max_length=10,
    )

    address = forms.CharField(
        label='address',
        max_length=150,
    )

    prefecture = forms.CharField(
        label='prefecture',
        max_length=5,
    )

    name = forms.CharField(
        label='shopname',
        max_length=150,
    )

    latitude = forms.FloatField(
        label='latitude',
    )

    longitude = forms.FloatField(
        label='longitude',
    )

    drivethrough = forms.BooleanField(
        label='drivethrough',
    )

    businesshour = forms.CharField(
        label='businesshour',
        max_length=500,
    )

    closed = forms.BooleanField(
        label='closed',
    )

    yuya = forms.BooleanField(
        label='yuya',
        initial=True,
    )

    non = forms.BooleanField(
        label='non',
    )

    monday = forms.CharField(
        label='monday',
        max_length=50,
    )

    tuesday = forms.CharField(
        label='tuesday',
        max_length=50,
    )

    wednesday = forms.CharField(
        label='wednesday',
        max_length=50,
    )

    thursday = forms.CharField(
        label='thursday',
        max_length=50,
    )

    friday = forms.CharField(
        label='friday',
        max_length=50,
    )

    saturday = forms.CharField(
        label='saturday',
        max_length=50,
    )

    sunday = forms.CharField(
        label='sunday',
        max_length=50,
    )

    holiday = forms.CharField(
        label='holiday',
        max_length=50,
    )

    add_day = forms.CharField(
        label = 'add_day',
        max_length = 30,
    )

map_for_starbucks/map/views.py
from typing import Any
from django.views.generic import ListView,FormView
from django.shortcuts import render
from .models import ShopList
from django.http import JsonResponse, HttpResponseRedirect
from django.urls import reverse
from . import forms
from . import my_functions

# Create your views here.

class MapView(ListView):
    template_name = 'map.html'
    context_object_name = 'ShopList'
    queryset = ShopList.objects.all()

class ExcelView(ListView):
    template_name = 'excel.html'
    context_object_name = 'ShopList'
    queryset = ShopList.objects.all()

class StatisticsView(ListView):
    template_name = 'statistics.html'
    context_object_name = 'ShopList'
    queryset = ShopList.objects.all()

def UpdateDataView(request):
    if request.method == 'POST':
        # POSTデータから値を取得
        row = request.POST.get('row')
        column = request.POST.get('column')
        value = request.POST.get('value')
        if value == 'true': value=True
        if value == 'false': value=False
        id = request.POST.get('id')

        # ここでデータベースの更新などを行う
        try:
            #変更内容が空白の場合エラー（たぶんModelの作り方を変えた方が良い）
            if value==None: raise ValueError("We can't use blank for the database.")

            # id に対応する行を取得
            shop = ShopList.objects.get(id=id)

            # モデルのフィールド名と一致するか確認し、一致する場合のみ値を設定
            if hasattr(shop, column):
                setattr(shop, column, value)
                shop.save()
                
                # クライアントにJSONレスポンスを返す
                response_data = {'message': 'データを更新しました。'}

                # 元のビューにリダイレクト
                return HttpResponseRedirect(reverse('map:excel'))
            else:
                return JsonResponse({'message': '指定された列が存在しません。'}, status=400)
        except ShopList.DoesNotExist:
            return JsonResponse({'message': '指定された ID の行が見つかりません。'}, status=404)
    else:
        # POST以外のHTTPメソッド（GETなど）の場合の処理を記述
        # 通常、POST以外のリクエストはエラーを返すか無視します
        return JsonResponse({'message': '無効なリクエストです。'}, status=400)

class import_list(FormView):
    template_name = 'import_list.html'
    form_class = forms.import_list_form
    
    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = self.form_class
        return context
    
    def form_valid(self, form):
        uploaded_files = self.request.FILES.getlist("visited_file")
        user = self.request.POST.get("user")
        diff_list,notfind_list,user = my_functions.flag_updater(uploaded_files[0],user)
        if uploaded_files[0].name.endswith(".html"):
            context = {'user':user,'diff_list':diff_list,'notfind_list':notfind_list}
            return render(self.request,'form_valid.html',context)
        else:
            context = {'form':form}
            return render(self.request,self.template_name,context)

class AddShopView(FormView):
    template_name= "add_shop.html"
    form_class = forms.ToDatabeseForm

map_for_starbucks/map/templates/add_shop.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
{% endblock %}

{% block content %}
<form method="POST" class="post-form" enctype="multipart/form-data">  
    {% csrf_token %}  
    {{ form.as_p }}
    <button type="submit" class="save btn btn-default">Save</button>  
</form>
{% endblock %}

map_for_starbucks/map/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <title>My Website</title>

    <meta name="viewport" content="width=device-width,initial-scale=1">

    <!-- Bootstrap CSSのリンク -->
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">

    {% block head %}{% endblock %}

</head>
<body>
    <!-- BootstrapのJavaScriptライブラリのリンク -->
    <script src="{% static 'js/scripts.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">My Website</a>
          <a class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </a>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                  <a class="nav-link" href="{% url 'map:map' %}">マップ</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link" href="{% url 'map:excel' %}">data</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'map:statistics' %}">統計情報</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'map:import_list' %}">インポート</a>
              </li>
            </ul>
          </div>
        </div>
    </nav>

    <!-- コンテンツブロック -->
    <div class="content">
        {% block content %}
        {% endblock %}
    </div>

</body>
</html>

map_for_starbucks/map/templates/excel.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" href="https://jsuites.net/v4/jsuites.css" type="text/css">
<link rel="stylesheet" href="https://bossanova.uk/jspreadsheet/v4/jexcel.css" type="text/css">
<link rel="stylesheet" href="{% static 'css/excelstyle.css' %}">
{% endblock %}

{% block content %}
<div>
  <input type="text" id="search-input" placeholder="Search...">
  <select id="search-column">
    <option value="all">All</option>
    <option value="Name">Name</option>
    <option value="Address">Address</option>
    <option value="yuya">yuya</option>
    <option value="non">non</option>
    <option value="Monday">Monday</option>
    <option value="Tuesday">Tuesday</option>
    <option value="Wednesday">Wednesday</option>
    <option value="Thursday">Thursday</option>
    <option value="Friday">Friday</option>
    <option value="Saturday">Saturday</option>
    <option value="Sunday">Sunday</option>
    <option value="Holiday">Holiday</option>
  </select>
  <button onclick="searchTable()">Search</button>
</div>
<div id="mytable"></div>
<script src="https://bossanova.uk/jspreadsheet/v4/jexcel.js"></script>
<script src="https://jsuites.net/v4/jsuites.js"></script>

<form id="update-form" action="{% url 'map:update_data' %}" method="post" style="display: none;">
  {% csrf_token %}
  <input type="hidden" id="update-row" name="row" value="">
  <input type="hidden" id="update-column" name="column" value="">
  <input type="hidden" id="update-value" name="value" value="">
  <input type="hidden" id="update-id" name="id" value="">
</form>

<script>
  var shops = [
    {% for shop in ShopList %}
        {"Name": "{{ shop.name }}","yuya": {{ shop.yuya|lower }}, "non": {{ shop.non|lower }}, "Address": "{{ shop.address }}",
         "Monday": "{{ shop.monday }}","Tuesday": "{{ shop.tuesday }}", 
         "Wednesday": "{{ shop.wednesday }}", "Thursday": "{{ shop.thursday }}",
         "Friday": "{{ shop.friday }}", "Saturday": "{{ shop.saturday }}", "Sunday": "{{ shop.sunday }}",
         "Holiday": "{{ shop.holiday }}", "ID": "{{ shop.id }}", "add_day": "{{ shop.add_day }}", 
         "yuya_last_visit": "{{shop.yuya_last_visit}}","yuya_frequency_of_visit": "{{ shop.yuya_frequency_of_visit }}",
         "non_last_visit": "{{shop.non_last_visit}}","non_frequency_of_visit": "{{ shop.non_frequency_of_visit }}"},
    {% endfor %}
  ];

  // IDの順番で行をソート
  shops.sort(function(a, b) {
    return a.ID - b.ID;
  });

  function decodeTime(encodedTime) {
    if (encodedTime == 'None') {
      // shop.timeがnullの場合、デフォルトの営業時間を設定
      return encodedTime;
    }
    return encodedTime.replace(/&#x27;/g, "").replace("(", "").replace(")", "").split(", ");
  }

  let dayOptions = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday', 'Holiday'];

  for (let i = 0; i < shops.length; i++) {
    for (let j = 0; j < dayOptions.length; j++){
      shops[i][dayOptions[j]] = decodeTime(shops[i][dayOptions[j]]);
    }
  }

  // 日付フォーマットを変換する関数
  function formatDate(dateString) {
      const parts = dateString.split('-');
      let year = parseInt(parts[0], 10);
      year = ('0000'+year).slice(-4);
      let month = parseInt(parts[1], 10);
      month = ('00'+month).slice(-2);
      let day = parseInt(parts[2], 10);
      day = ('00'+day).slice(-2);
      const formatDate = year+'/'+month+'/'+day
      return formatDate;
  }
  
  // "add_day" 列の値を日付に変換
  for (let i = 0; i < shops.length; i++) {
      const addDay = shops[i]['add_day'];
      shops[i]['add_day'] = formatDate(addDay);

      const yuya_frequency_of_visit = shops[i]['yuya_frequency_of_visit'];
      if (yuya_frequency_of_visit == 'None') {
        shops[i]['yuya_frequency_of_visit'] = 0;
      }

      const non_frequency_of_visit = shops[i]['non_frequency_of_visit'];
      if (non_frequency_of_visit == 'None') {
        shops[i]['non_frequency_of_visit'] = 0;
      }
  }

  const headers = [
    { type: 'text', title: 'Name', width: 200 },
    { type: 'dropdown', title: 'yuya', width: 100, source: ['true', 'false'] },
    { type: 'dropdown', title: 'non', width: 100, source: ['true', 'false'] },
    { type: 'text', title: 'Address', width: 300 },
    { type: 'text', title: 'Monday', width: 100 },
    { type: 'text', title: 'Tuesday', width: 100 },
    { type: 'text', title: 'Wednesday', width: 100 },
    { type: 'text', title: 'Thursday', width: 100 },
    { type: 'text', title: 'Friday', width: 100 },
    { type: 'text', title: 'Saturday', width: 100 },
    { type: 'text', title: 'Sunday', width: 100 },
    { type: 'text', title: 'Holiday', width: 100 },
    { type: 'text', title: 'ID', width:50},
    { type: 'text', title: 'add_day', width: 100 },
    { type: 'text', title: 'yuya_last_visit', width: 100 },
    { type: 'text', title: 'yuya_frequency_of_visit', width: 50},
    { type: 'text', title: 'non_last_visit', width: 100 },
    { type: 'text', title: 'non_frequency_of_visit', width: 50},
  ];

  const myTable = jspreadsheet(document.getElementById('mytable'), {
    data: shops,
    columns: headers,
    onchange: updateDataToDatabase,
  });

  function updateDataToDatabase(el, cell, x, y, value, oldValue) {
    console.log('セルの内容が変更されました');
    console.log(headers[x].title, y, value); // 変更されたデータの情報をログに出力

    // フォームにセルの内容を設定
    const updateRowInput = document.getElementById('update-row');
    const updateColumnInput = document.getElementById('update-column');
    const updateValueInput = document.getElementById('update-value');
    const updateIdInput = document.getElementById('update-id');

    updateRowInput.value = y;
    updateColumnInput.value = headers[x].title;
    updateValueInput.value = value;
    updateIdInput.value = shops[y].ID;
    
    // 以下、ajaxリクエストを用いた非同期処理用
    // Ajaxリクエストを作成
    let xhr = new XMLHttpRequest();
    xhr.open('POST', '{% url "map:update_data" %}', true);
    xhr.setRequestHeader('X-CSRFToken', '{{ csrf_token }}'); // CSRFトークンを設定

    xhr.onreadystatechange = function() {
      if (xhr.readyState === 4) {
        if (xhr.status === 200) {
          // リクエストが成功した場合の処理
          console.log('データが更新されました。');
        } else {
          // リクエストが失敗した場合の処理
          console.error('データの更新に失敗しました。');
        }
      }
    };

    // フォームデータを送信
    let formData = new FormData();
    formData.append('row', updateRowInput.value);
    formData.append('column', updateColumnInput.value);
    formData.append('value', updateValueInput.value);
    formData.append('id', updateIdInput.value);

    xhr.send(formData);

  }

  function searchTable() {
    const searchValue = document.getElementById('search-input').value;
    const searchColumn = document.getElementById('search-column').value;

    // ドロップダウンで選択した列に対してのみ検索を行う
    if (searchColumn === "all") {
      myTable.search(searchValue, false);
      console.log('all')
    } else {
      myTable.search(searchValue, false, false, columns=searchColumn);
      console.log(searchColumn)
    }
  }
  // 初期値をnameに設定
  document.getElementById('search-column').value = "Name";
</script>
{% endblock %}

map_for_starbucks/map/templates/form_valid.html
<!DOCTYPE html>
{% extends 'base.html' %}

{% block head %}
<style>
    body {
        font-family: Arial, sans-serif;
        background-color: #f2f2f2;
    }

    h1 {
        color: #333;
        text-align: center;
        margin-top: 50px;
    }

    .button-container {
        text-align: center;
        margin-top: 20px;
    }

    .button-container a {
        display: inline-block;
        margin-right: 10px;
        padding: 10px 20px;
        background-color: #007bff;
        color: #fff;
        text-decoration: none;
        border-radius: 5px;
    }

    .button-container a:hover {
        background-color: #0056b3;
    }
</style>
{% endblock %}

{% block content %}
  <h1>{{user}}'s diff is compleated!</h1>
  <a href="{% url 'map:import_list' %}">back</a>
  <a href="{% url 'map:map' %}">map</a>
  <div>
    {{ diff_list }}
  </div>
  <div>
    {{ notfind_list}}
  </div>
{% endblock %}

map_for_starbucks/map/templates/import_list.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}

{% block head %}
{% endblock %}

{% block content %}
<form method="POST" class="post-form" enctype="multipart/form-data">  
  {% csrf_token %}  
  {% bootstrap_form form %}
  {% bootstrap_button button_type="submit" content="Save" size="lg" %} 
</form>
{% endblock %}

map_for_starbucks/map/templates/simple_template.html
<!DOCTYPE html>
{% extends 'base.html' %}

{% block head %}
{% endblock %}

{% block content %}
  <h1>Hello, World!</h1>
{% endblock %}

map_for_starbucks/map/templates/statistics.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% block head %}
{% endblock %}

{% block content %}
<div>
  <script>
    var shops = [
      {% for shop in ShopList %}
        {% if shop.latitude %}
          {"prefecture": "{{ shop.prefecture }}", "yuya": {{ shop.yuya|lower }}, "non": {{ shop.non|lower }}},
        {% endif %}
      {% endfor %}
    ];

    var countByPrefectureYuya = {};
    var countByPrefectureNon = {};

    var prefecturesInOrder = [
      "北海道","青森県","岩手県","宮城県","秋田県",
      "山形県","福島県","茨城県","栃木県","群馬県",
      "埼玉県","千葉県","東京都","神奈川県","新潟県",
      "富山県","石川県","福井県","山梨県","長野県",
      "岐阜県","静岡県","愛知県","三重県","滋賀県",
      "京都府","大阪府","兵庫県","奈良県","和歌山県",
      "鳥取県","島根県","岡山県","広島県","山口県",
      "徳島県","香川県","愛媛県","高知県","福岡県",
      "佐賀県","長崎県","熊本県","大分県","宮崎県",
      "鹿児島県","沖縄県","全国",
    ];

    // 全国のyuyaとnonの総和計算用
    var nationalYuyaTotal = 0;
    var nationalNonTotal = 0;

    for (var i = 0; i < prefecturesInOrder.length; i++) {
      var currentPrefecture = prefecturesInOrder[i];
      var yuyaCount = 0;
      var nonCount = 0;

      for (var j = 0; j < shops.length; j++) {
        if (shops[j].prefecture === currentPrefecture) {
          if (shops[j].yuya === true) {
            yuyaCount++;
            nationalYuyaTotal++;
          }

          if (shops[j].non === true) {
            nonCount++;
            nationalNonTotal++;
          }
        }
      }

      countByPrefectureYuya[currentPrefecture] = yuyaCount;
      countByPrefectureNon[currentPrefecture] = nonCount;
    }

    var countByPrefectureShops = {}; // 都道府県ごとの店舗数を格納するオブジェクト
    var countNationalShops = 0;

    // 都道府県ごとの店舗数をカウント
    for (var m = 0; m < prefecturesInOrder.length; m++) {
      var currentPrefecture = prefecturesInOrder[m];
      var shopCount = 0;

      for (var n = 0; n < shops.length; n++) {
        if (shops[n].prefecture === currentPrefecture) {
          countNationalShops++;
          shopCount++;
        }
      }

      countByPrefectureShops[currentPrefecture] = shopCount;
    }

    document.write("<table>");
    document.write("<tr>");
    document.write("<th></th>");
    document.write("<th>店舗数</th>");
    document.write("<th>yuya</th>");
    document.write("<th style='padding-right: 20px;'></th>");
    document.write("<th>non</th>");
    document.write("<th style='padding-right: 20px;'></th>");
    document.write("</tr>");
    
    for (var o = 0; o < (prefecturesInOrder.length)-1; o++) {
      var currentPrefectureTable = prefecturesInOrder[o];
      var yuyaRatio = countByPrefectureYuya[currentPrefectureTable] / countByPrefectureShops[currentPrefectureTable];
      var nonRatio = countByPrefectureNon[currentPrefectureTable] / countByPrefectureShops[currentPrefectureTable];

      document.write("<tr>");
      document.write("<td>" + currentPrefectureTable + "</td>");
      document.write("<td>" + countByPrefectureShops[currentPrefectureTable] + "</td>");
      document.write("<td>" + countByPrefectureYuya[currentPrefectureTable] + "</td>");
      document.write("<td style='padding-right: 20px;'>" + yuyaRatio.toFixed(2) + "</td>");
      document.write("<td>" + countByPrefectureNon[currentPrefectureTable] + "</td>");
      document.write("<td style='padding-right: 20px;'>" + nonRatio.toFixed(2) + "</td>");
      document.write("</tr>");
    }
    
    document.write("<tr>");
    document.write("<td>全国</td>");
    document.write("<td>" + countNationalShops + "</td>");
    document.write("<td>" + nationalYuyaTotal + "</td>");
    document.write("<td style='padding-right: 20px;'>" + (nationalYuyaTotal / countNationalShops).toFixed(2) + "</td>");
    document.write("<td>" + nationalNonTotal + "</td>");
    document.write("<td style='padding-right: 20px;'>" + (nationalNonTotal / countNationalShops).toFixed(2) + "</td>");
    document.write("</tr>");
    
    document.write("</table>");
  </script>
</div>
{% endblock %}